spring:
  application:
    name: api-gateway

  cloud:
    loadbalancer:
      rule: random
    gateway:
        routes:
        - id: product-service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product-service/**

        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**

        - id: inventory-service
          uri: http://localhost/3001
          predicates:
            - Path=/inventory-service/**

        - id: customer-service
          uri: http://localhost/5000
          predicates:
            - Path=/customer-service/**


